making_tables <- function(results_list, averaging = FALSE, as_matrix = FALSE){
  # function to write utility results of synthetic data generated by several different 
  ## vine topologies to a list containing a matrix collecting the results by measure;
  # the utility lists have to be written into the results_list and should be named after their specific vine topology;
  # if averaging is set to TRUE the p_synth results are summarized in through computing the average;
  # if as_matrix is set to TRUE the matrices containing each the results of one measure collected in the list
  ## are merged while keeping row and column names (better format for saving)
  
  
  nice_list <- list("acc" = matrix(, nrow = 3), "F" = matrix(, nrow = 3), "AUC" = matrix(, nrow = 3), "MCC" = matrix(, nrow = 3))
  
  # looping over different synthetic data generating vine topologies
  for(t in 1: length(results_list)){
    
      current_results <- results_list[[t]]
      name <- names(results_list)[t]
  
      # looping over no. of synthetic data sets  
      for (i in 1:length(current_results)) {
        
          current_results_p <- current_results[[i]]
          
          # looping over utility measures to display (acc, Fmeasure, AUC, MCC)
          for(j in c(2:5)){
            
              nice_list[[j - 1]] <- cbind(nice_list[[j - 1]], current_results_p[[j]] %>% unlist)
              
          }
        
      }
  
  }
  
  for (k in 1:4) {
    nice_list[[k]] <- nice_list[[k]][, -1]
    l <- dim(nice_list[[k]])[2]
    
    colnames(nice_list[[k]]) <- rep(names(results_list), each = length(current_results))
    
    if(averaging == TRUE){
        for (i in 1:length(names(results_list))) {
            average <- nice_list[[k]][, c(colnames(nice_list[[k]]) == names(results_list)[i])] %>% matrix(, nrow = 3) %>% rowMeans()
            nice_list[[k]] <- cbind(nice_list[[k]],  average) 
        }
      
        nice_list[[k]] <- nice_list[[k]][, -c(1:l)]
        colnames(nice_list[[k]]) <- names(results_list)
        
    }
    
  }
  
  if(as_matrix == TRUE){
    
      nice_list <- do.call(rbind, nice_list)
    
  }
  
  
  
  return(nice_list)
}